### PR TITLE
Add index as config options

### PR DESCRIPTION
**Pull request by apoorva-saxena**

### CODE REVIEW

**Comment by apoorva-saxena** [comment]
This will provide the option to add createdAt and updatedAt as index. Is there some known issue with the test, as the test failure doesn't seem related to my change

**Review by clarkbw — APPROVED** [review]
This looks good.  The test failures aren't related to what you've done but if you have a chance could you dig into it and fix it up?  Looks like an eslint issue.

**Comment by apoorva-saxena** [comment]
The issue seems to be due to: https://github.com/gulpjs/undertaker/issues/54 , have fixed the eslint issue

**Comment by apoorva-saxena** [comment]
Have raised an issue: https://github.com/gulpjs/undertaker/issues/88

**Comment by apoorva-saxena** [comment]
@clarkbw The tests seem to pass locally for me with node5. Should we merge this?

**Comment by clarkbw** [comment]
> @clarkbw The tests seem to pass locally for me with node5. Should we merge this?

Sure, lets merge this and I'll get rid of Gulp in a followup.

**Pull request merged**
